version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.7
    commands:
      - pip3 install pytest
  build:
    commands:
      - python -m pytest --junitxml=pytest_reports/pytest_report.xml
      - python -m pytest --junitxml=pytest_reports/pytest_report22.xml

reports:
  pytest_reports:
    files:
      - pytest_report.xml
    base-directory: pytest_reports/
    file-format: JUNITXML
---
 reports:
  pytest_reports222:
    files:
      - pytest_report22.xml
    base-directory: pytest_reports/
    file-format: JUNITXML
